export default {
	// 基本信息
	archiveCode: '', // 档案编码
	patientName: '', // 姓名
	sex: '', // 性别
	birthDate: '', // 出生日期年月日
	birthTime: '', // 出生日期时分秒
	birthNumber: '', // 出生证号
	hospitalType: '1', // 医院地区类型
	birthOrg: '666', // 出生医院
	healthCard: '', // 电子健康证
	nationalityCode: '156', // 国籍
	idCardType: '01', // 证件类型
	idCardNumber: '', // 证件号码
	nationCode: '01', // 民族
	// 管理信息
	liveProvinceCode: '', // 家庭地址-省份编码
	liveProvince: '', // 家庭地址-省份名称
	liveCityCode: '', // 家庭地址-市级编码
	liveCity: '', // 家庭地址-市级名称
	liveCountyCode: '', // 家庭地址-区县编码
	liveCounty: '', // 家庭地址-区县名称
	liveStreetCode: '', // 家庭地址-乡镇/街道编码
	liveStreet: '', // 家庭地址-乡镇/街道名称
	currentAddrDetail: '', // 家庭地址-具体地址
	resProvinceCode: '', // 户籍地址-省份编码
	resProvince: '', // 户籍地址-省份名称
	resCityCode: '', // 户籍地址-市级编码
	resCity: '', // 户籍地址-市级名称
	resCountyCode: '', // 户籍地址-区县编码
	resCounty: '', // 户籍地址-区县名称
	resStreetCode: '', // 户籍地址-乡镇/街道编码
	resStreet: '', // 户籍地址-乡镇/街道名称
	permanentAddrDetail: '', // 户籍地址-具体地址
	currentAddrCode: '', // 现住地址编码
	accountAttribute: '', // 户口属性
	regionCode: '', // 区域划分编码
	permanentAddrCode: '', // 户籍县国标
	archiveState: '1', // 在册情况
	resAttribute: '', // 户籍属性
	filingUniteName: '', // 建档单位
	filingPerson: '', // 建档人
	filingDate: '', // 建档日期
	filingUnite: '', // 建档单位编码
	manageDeptCode: '', // 现管单位编码
	manageTime: '', // 起始管理日期
	// 出生信息
	birthWeight: '', // 出生体重
	parity: '', // 胎次
	gestationalAge: '', // 胎龄-周
	foetusDay: '', // 胎龄-天
	hivType: '', // Hiv类型
	chDiseaseSign: '2', // 是否有先天性心脏病
	chDiseaseDesc: '', // 是否有先天性心脏病-说明
	immuneDeficiencySign: '2', // 是否有原发性免疫功能缺陷
	immuneDeficiencyDesc: '', // 是否有原发性免疫功能缺陷-说明
	otherDiseasesType: '2', // 出生时是否有其他疾病
	diseaseDesc: '', // 出生时是否有其他疾病-说明
	allergySign: '2', // 是否有过敏史
	allergyDesc: '', // 是否有过敏史-说明
	vaccinationTabooSign: '2', // 是否有接种禁忌
	vaccinationTabooDesc: '', // 是否有接种禁忌-说明
	contraindicatedVaccine: [], // 禁忌疫苗列表
	infectiousHistory: '2', // 是否有既往传染病史
	infectiousHistoryDesc: '', // 是否有既往传染病史-说明
	// 监护人信息
	motherName: '', // 母亲姓名
	motherTel: '', // 母亲电话
	motherIdType: '', // 母亲证件类型
	motherIdCard: '', // 母亲证件号码
	fatherName: '', // 父亲姓名
	fatherTel: '', // 父亲电话
	fatherIdType: '', // 父亲证件类型
	fatherIdCard: '', // 父亲证件号码
	contacts: '', // 其他监护人姓名
	contactsTel: '', // 其他监护人电话
	contactsRelCode: '', // 其他监护人关系
	remark: '', // 备注
	// 家族史
	familyImmunefunctionSign: '2', // 家族成员是否有免疫功能异常
	familyImmunefunctionDesc: '', // 家族成员是否有免疫功能异常-说明
	familialInheritanceSign: '2', // 家族成员是否有遗传病史
	familialInheritanceDesc: '', // 家族成员是否有遗传病史-说明
	hepatitisMother: '1', // 母亲HBsAG
	motherHbsagDesc: '', // 母亲HBsAG-说明
	motherHivPositive: '1', // 母亲HIV标志
	motherHivDesc: '', // 母亲HIV标志-说明
	motherDiseaseSign: '2', // 母亲其他疾病
	motherDiseaseDesc: '', // 母亲其他疾病-说明
}
